# Generated by Django 4.2.16 on 2024-10-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_teammember_alter_blogimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="image",
            field=models.ImageField(default="profile.jpg", upload_to="team_members"),
        ),
    ]
