# Generated by Django 4.2.16 on 2024-10-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_teammember_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="image",
            field=models.ImageField(
                default="/media/profile.jpg", upload_to="team_members"
            ),
        ),
    ]
