# Generated by Django 4.2.16 on 2024-10-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_teammember_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
