# Generated by Django 4.2.16 on 2024-10-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_property_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo", name="about_us", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(
                upload_to="https://meet.google.com/ife-dtmv-ijdproperty"
            ),
        ),
    ]
