# Generated by Django 4.2.16 on 2024-10-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_siteinfo_about_us_alter_propertyimage_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="property", name="listing_count",),
        migrations.AlterField(
            model_name="property",
            name="bathroom_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="property",
            name="bedroom_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="property",
            name="home_unit_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="property",
            name="parking_space_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
