# Generated by Django 4.2.16 on 2024-10-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_property_listing_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="slug",
            field=models.SlugField(
                default="<function uuid4 at 0x7fe0a01d8550>",
                max_length=255,
                unique=True,
            ),
        ),
    ]
