# Generated by Django 4.2.16 on 2024-10-07 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_property_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="property",
            name="slug",
            field=models.SlugField(
                default="<function uuid4 at 0x7fa8702ef550>",
                max_length=255,
                unique=True,
            ),
        ),
    ]
