# Generated by Django 4.2.16 on 2024-10-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_property_created_at_alter_property_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[("APARTMENT", "apartment"), ("duplex", "DUPLEX")],
                default="duplex",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="slug",
            field=models.SlugField(
                default="<function uuid4 at 0x7fb350748550>",
                max_length=255,
                unique=True,
            ),
        ),
    ]
