# Generated by Django 4.2.16 on 2024-10-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_property_property_type_alter_property_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="slug",
            field=models.SlugField(
                default="<function uuid4 at 0x7fa7a8118550>",
                max_length=255,
                unique=True,
            ),
        ),
    ]
