# Generated by Django 4.2.16 on 2024-10-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_property_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="duration",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="property_type",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="style",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="year_of_execution",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="slug",
            field=models.SlugField(
                default="234f184f-9742-4d0d-9862-8ccc1b1af549",
                max_length=255,
                unique=True,
            ),
        ),
    ]
