# Generated by Django 5.1.1 on 2024-10-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_property_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(default='0901a48a-a1fc-4f9e-8e63-68f0498685d2', max_length=255, unique=True),
        ),
    ]
