# Generated by Django 4.2.16 on 2024-10-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_project_duration_project_property_type_project_style_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="style",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="slug",
            field=models.SlugField(
                default="21671a58-fdc2-4cdf-862a-7094a15849b9",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="PropertyAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amenity", models.CharField(max_length=50)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_amenities",
                        to="app.property",
                    ),
                ),
            ],
        ),
    ]
