# Generated by Django 4.2.16 on 2024-10-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_project_style_alter_property_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="slug",
            field=models.SlugField(
                default="e4954e87-566c-45a2-bb17-0d9efcad7a45",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(upload_to="property"),
        ),
    ]
