# Generated by Django 5.1.1 on 2024-10-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_property_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(default='ada15864-a5db-425f-8af0-ff82e03803ba', max_length=255, unique=True),
        ),
    ]
