# Generated by Django 5.1.1 on 2024-10-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_project_duration_project_property_type_project_style_and_more'),
        ('app', '0017_alter_property_slug'),
    ]

    operations = [
    ]
