# Generated by Django 5.1.1 on 2024-10-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_property_slug_alter_propertyimage_image'),
        ('app', '0018_merge_20241013_1420'),
    ]

    operations = [
    ]
