# Generated by Django 5.1.1 on 2024-10-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_blog_conver_photo_blog_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='client',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='collaborator',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='location',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='scope',
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(default='525e35a5-6717-4e36-a8d4-8f62f696e1f6', max_length=255, unique=True),
        ),
    ]
