# Generated by Django 5.1.1 on 2024-10-16 14:17

import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_conver_photo_blog_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=markdownfield.models.MarkdownField(rendered_field='description_rendered'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(default='ebcef8ba-8775-4e15-9753-6700b7f118c5', max_length=255, unique=True),
        ),
    ]
