# Generated by Django 5.1.1 on 2024-10-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_property_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiUploadActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(default='440c5df9-a56b-44a4-a193-41434d946157', max_length=255, unique=True),
        ),
    ]
